[package]
name = "broth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.1"
log = "0.4.20"
png = "0.17.10"
thiserror = "1.0.56"
vulkanalia = "0.22.0"
winit = "0.29.9"
